"""Users table types updated

Revision ID: 4455ef4ff529
Revises: cd923afc6daa
Create Date: 2025-07-15 19:52:54.496145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4455ef4ff529'
down_revision: Union[str, Sequence[str], None] = 'cd923afc6daa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Users', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('Users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Users', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
