"""Email Accounts Table added

Revision ID: 9a3b841c4db6
Revises: 4455ef4ff529
Create Date: 2025-07-27 22:16:40.727141

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9a3b841c4db6"
down_revision: Union[str, Sequence[str], None] = "4455ef4ff529"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_accounts",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("provider", sa.String(), nullable=True),
        sa.Column("credentials", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["Users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("email_accounts")
    # ### end Alembic commands ###
