"""UserEmailAccount fields updated for push notifications

Revision ID: fe66e8d59ac2
Revises: 9a3b841c4db6
Create Date: 2025-08-05 13:45:26.615379

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fe66e8d59ac2"
down_revision: Union[str, Sequence[str], None] = "9a3b841c4db6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "email_accounts", sa.Column("is_credentials_valid", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "email_accounts", sa.Column("notification_config", sa.JSON(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("email_accounts", "notification_config")
    op.drop_column("email_accounts", "is_credentials_valid")
    # ### end Alembic commands ###
